package de.ampada.tmsaddon.enums;

public enum RoleEnum {
    /*BAGHERI: NO USAGE OF ROLE_ADMIN FOUND IN RFP! SO IT JUST WRITTEN AND NEVER USED.
    * ROLE_DUMMY WILL BE ADDED TO ALL USERS AND IT'S BENEFIT SHOWS ON WHEN ANOTHER ROLES COMES TO SYSTEM*/
    ROLE_ADMIN, ROLE_USER, ROLE_DUMMY
}
